

////////////////////////////////////////////////////////////////////////////////
// File: vortex_status_if.sv (CORRECTED VERSION)
// Description: Status Interface for Vortex Execution Monitoring
// Description: Status interface - ONLY signals actually provided by Vortex DUT

// SIGNAL SOURCES:
//   - DUT provides:   busy (only!)
//   - TB generates:   cycle_count, instr_count, ebreak_detected

//
// IMPORTANT CHANGES:
//   - Removed performance counters (cycle_count, instr_count) - NOT provided by DUT
//   - Removed PC, pipeline state - NOT provided by DUT
//   - Removed assertions on unavailable signals
//   - Kept only: busy, ebreak_detected
//
// The DUT provides minimal status outputs. Performance monitoring must be done
// via CSR reads or by tracking in the testbench.
//
// Author: Vortex UVM Team (Fixed Version)
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////

`ifndef VORTEX_STATUS_IF_SV
`define VORTEX_STATUS_IF_SV

interface automatic vortex_status_if (
    input logic clk,
    input logic reset_n
);

    //==========================================================================
    // SIGNALS FROM DUT (ONLY BUSY!)
    //==========================================================================
    logic       busy;               // Core is executing (from Vortex RTL)
    
    //==========================================================================
    // SIGNALS FROM TESTBENCH (GENERATED BY TB)
    // FIX (vopt-7061): declared as 'wire' so tb_top can drive via continuous
    // 'assign'. A 'logic' driven by assign from an external module conflicts
    // with Questa's ownership model. 'wire' has no single-owner restriction.
    //==========================================================================
    wire        ebreak_detected;    // TB detects completion via idle threshold
    wire [63:0] cycle_count;        // TB counts cycles
    wire [63:0] instr_count;        // TB estimates from memory activity
    wire [31:0] pc;                 // TB tracks if available (optional)
    
    // Derived signals
    logic       idle;
    assign idle = !busy;
    
    //==========================================================================
    // MODPORTS
    //==========================================================================
    
    // DUT only provides busy
    modport dut (
        input  clk,
        input  reset_n,
        output busy
    );
    
    // TB writes counters, reads busy
    modport tb (
        input  clk,
        input  reset_n,
        input  busy,
        output ebreak_detected,
        output cycle_count,
        output instr_count,
        output pc,
        input  idle
    );
    
// Monitor reads everything (uses clocking block for sampling)
modport monitor (
    clocking monitor_cb,
    input  clk,
    input  reset_n
);

    
    //==========================================================================
    // CLOCKING BLOCKS
    //==========================================================================
    
    clocking monitor_cb @(posedge clk);
        default input #1step output #1ns;
        input busy;
        input ebreak_detected;
        input cycle_count;
        input instr_count;
        input pc;
        input idle;
    endclocking
    
    clocking driver_cb @(posedge clk);
        default input #1step output #1ns;
        input busy;
        input idle;
    endclocking
    
    //==========================================================================
    // ASSERTIONS (only on DUT-provided signals)
    //==========================================================================
    
    // Check busy eventually deasserts (no permanent hang)
    property busy_eventually_idles_p;
        @(posedge clk) disable iff (!reset_n)
        $rose(busy) |-> ##[1:10000] $fell(busy);
    endproperty
    
    assert_busy_eventually_idles: assert property (busy_eventually_idles_p)
        else $warning("[STATUS_IF @ %0t] Busy stuck high for >10000 cycles!", $time);
    
    // //==========================================================================
    // // INITIALIZATION
    // //==========================================================================
    // initial begin
    //     // Initialize TB-controlled signals
    //     ebreak_detected = 1'b0;
    //     cycle_count = 64'h0;
    //     instr_count = 64'h0;
    //     pc = 32'h0;
    // end
    
endinterface : vortex_status_if

`endif // VORTEX_STATUS_IF_SV